# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: "Change Request"
description: Issue to track a change
title: "Change: Your Change Request title"
labels: ["codeowner_review"]
body:
  - type: checkboxes
    attributes:
      label: Change Request Type
      options:
        - label: Feature Request/Modification
        - label: Component Request/Modification
          required: true
  - type: textarea
    attributes:
      label: Reason for the Change Request?
      description: |
        - Exact description of the Change Request
        - Estimate the effort, resources, risk for the realization
        - Verification measures
        - Impact to users of the feature/component
        - Use following template within a PR and link it to this issue
          [Change Management Feature Request Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_feature_template.html) needs to be used
          [Change Management Component Request Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_component_template.html) needs to be used
    validations:
      required: true
  - type: textarea
    attributes:
      label: How is the change realized?
      description: |
        - Details on implementation approach
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Affected work products
      options:
        - label: Requirements are affected by this change?
        - label: Architecture are affected by this change?
        - label: Analysis are affected by this change?
        - label: Detailed Designs are affected by this change?
          required: true
  - type: textarea
    attributes:
      label: Impact analysis
      description: |
        - Details on the impacted work products
        - Use the following template and/or run the impact analysis tool provided and link it to the PR containing the
        [Change Management Impact Analysis Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_impact_analysis_template.html) needs to be used
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Safety or Security relevance
      options:
        - label: Safety relevant
        - label: Security relevant
  - type: textarea
    attributes:
      label: ASIL classification
      description: Add ASIL classification, e.g. ASIL_B or ASIL_D
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Expected Implementation Version
      options:
        - 0.5
        - 1.0
      default: 0
    validations:
      required: false
